import Logo from '../../Assets/icono.png'


export const Eat={
    starters:[
        {   caption:'Toast',
            price:3.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Toast with butter',
            price:5.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Fruit cocktail',
            price:7.29,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Cream chesse',
            price:7.40,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Vegetable`s cream',
            price:8.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Chirizo slices',
            price:9.23,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Chinese butterflies',
            price:15.50,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Squid slices',
            price:20.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},

    ],
    mainDishes:[
        {   caption:'Veal fillet',
            price:15.31,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Uruguayan steak',
            price:12.35,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Fried chickend',
            price:10.63,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Ribs with honey',
            price:10.66,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Beef steak',
            price:14.15,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Pork steak',
            price:9.43,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Tuna',
            price:15.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Lobster',
            price:27.33,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},        
    ],
    pizza:[
        {   caption:'Cheese',
            price:5.23,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Vegetables',
            price:7.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Pineapple',
            price:5.45,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Onion',
            price:5.55,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Squid',
            price:14.65,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Chirizo',
            price:9.34,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Tuna',
            price:15.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},          
    ],
    dessert:[
        {   caption:'Ice cream ball',
            price:5.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'cake',
            price:7.57,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Tiramisu',
            price:5.89,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
    ],
    bar:[
        {   caption:'water bottle',
            price:2.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Coca-cola',
            price:3.87,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Conchita',
            price:4.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'Rontel wiskey bottle',
            price:13.34,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'wine bottle Lechnsin 2018 ',
            price:15.09,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'wine bottle Lechnsin 2015 ',
            price:20.12,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'wine bottle Lechnsin 2020 ',
            price:20.45,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
    ],
    garrison:[
        {   caption:'white rice',
            price:2.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'conger rice',
            price:3.00,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},
        {   caption:'seasoned rice',
            price:4.54,
            logo:Logo,
            info:'sde erf er grgge erg ghy uyf fg hfgok df if90jj 90j0jnjdfn ionnsd dsf  gt j d ffg gf dhfd fdh dg fdgh gh'},

    ],
}


